{
  "env": {
    "node": true,
    "es6": true,
    "mocha": true
  },
  "extends": "airbnb-base",
  "rules": {
    "global-require": 0,
    "import/no-dynamic-require": 0,
    "class-methods-use-this": 0,
    "no-param-reassign": 0,
    "no-await-in-loop": 0
  }
}
